### ISSUE TITLE
[spec] Consider storing log(N) in scrypt recipient line

### ISSUE THREAD

**Issue by str4d** [FiloSottile/age#10]
The scrypt library I am using in my Rust implementation takes log(N) as a parameter, which requires a bit of additional logic to handle (computing log(N) from N and verifying that N was an exact power of 2).

Per [RFC 7914 section 6](https://tools.ietf.org/html/rfc7914#section-6):

> N: CPU/Memory cost parameter, must be larger than 1, a power of 2, and less than 2^(128 * r / 8).

If N must always be a power of 2, then we could simplify the format and implementations by instead storing log(N). This would remove the need for power-of-two checks, and converting log(N) to N for APIs that take N is a trivial bitshift.

**Comment by FiloSottile** [comment]
Yeah this is a good idea. Let's do that.
