### ISSUE TITLE
age -d -i does not support aes256-cbc encrypted ed25519 private keys

### ISSUE THREAD

**Issue by martinseener** [FiloSottile/age#100]
## Environment

* OS: Linux Mint 19.3
* age version: https://github.com/FiloSottile/age/commit/9fdb1256415935a4425b6b607ea843ff85b854ae

## What were you trying to do
I have encrypted a file using `age -r "ssh-ed25519 AAAA..." -o testfile.age testfile` and then wanted to decrypt it using `age -d -i ~/.ssh/id_ed25519 testfile.age`

## What happened
age errored that it does not support aes-cbc mode:
```
Enter passphrase for "/home/myusername/.ssh/id_ed25519": 
Error: failed to decrypt SSH key file: ssh: unknown cipher "aes256-cbc", only supports "aes256-ctr"
```
I created my key some years ago with `ssh-keygen -t ed25519`
I expect age to support decrypting aes-cbc as well (128/256bits)

Interesting side note: My RSA private key is encrypted using aes-128-cbc but using it with age works at this point. Not sure why though.

**Comment by str4d** [comment]
Looks like the default cipher that `ssh-keygen` uses to encrypt keys was switched from `aes256-cbc` to `aes256-ctr` ([issue](https://bugzilla.mindrot.org/show_bug.cgi?id=2754)) in OpenSSH 7.6, released 2017-10-03.

AFAICT those are the only two ciphers that have ever been default for `ssh-keygen`, so if we support both of those, that will cover basically all encrypted OpenSSH keys.

**Comment by RKinsey** [comment]
Unfortunately, this isn't really fixable from here. x/crypto/ssh explicitly checks for the "aes256-ctr" string and fails otherwise when using passphrase-protected keys. I'll open an issue to see if excluding CBC was intentional.

**Comment by RKinsey** [comment]
I submitted a change to fix this to x/crypto, so it's closable once the commit is merged
