### ISSUE TITLE
Proposal - allow user defined line width for ASCII armor

### ISSUE THREAD

**Issue by sac001** [FiloSottile/age#106]
Hi,

I would like to see an option in age where users can optionally define a line width
for ASCII armor, like age -a 32 etc., so that encrypted content pasted on social
media sites or in messengers etc. looks nice.

For example some base64 encoders allow this and older ones have IIRC no problems
decoding such messages.

**Comment by dcand** [comment]
pass the output through fmt(1)

**Comment by FiloSottile** [comment]
The armor format is not meant to be the only encoding for age files or to work for everyone, it's just there to give a strict homogeneous standard for the default. I think it's best if it stays simple and strict, but you can easily pipe the binary output of age into any encoder that works for you.
