### ISSUE TITLE
-----BEGIN AGE ENCRYPTED PAYLOAD----- instead of FILE ...

### ISSUE THREAD

**Issue by sac001** [FiloSottile/age#107]
Hi,
while both, age and GnuPG are using armor headers/footers like MESSAGE or in age's case FILE
why not use a generic term like PAYLOAD? I am no native English speaker but something like
PAYLOAD, or maybe a word like CONTENT, would look IMHO better when sending messages and not only files.

Well, only a suggestion.

**Comment by str4d** [comment]
To me, this is working as intended. age is designed to be a file encryption tool, not a generic message encryption layer. The use of `FILE` in the PEM encoded format is a useful reminder in the "user interface" of the age format.
