### ISSUE TITLE
spec: serious security

### ISSUE THREAD

**Issue by pznknmtb** [FiloSottile/age#118]
there are "a few things missing" that are needed to find out if this "product" is a serious encryption tool.
* complete and compact description of the algorithm
* list of security features (other than "secure encryption", e.g. "forward secrecy") and how they were implemented
* proper threat analysis

PS : I could not find any security review of this product, maybe it's just well hidden...

**Comment by FiloSottile** [comment]
It doesn't sound like this started in a way that would lead to a productive conversation, and this issue doesn't suggest anything that isn't already done or tracked elsewhere, so I'm going to close this.

If age doesn't have some kind of review that you are seeking, I invite you to perform or sponsor one, or to use one of the many alternatives.

**Comment by cyb3rz3us** [comment]
I know this is closed but regardless, here are some counters to the OP "concerns"...

**First**, the first two bullets are easily addressed by one simply reviewing the white paper published by _FiloSottie_ which is linked in the project README.  I have also provided the same link [here](https://docs.google.com/document/d/11yHom20CrsuX8KQJXBBw04s80Unjv8zCg_A7sPAX_9Y/preview).

**Next**, details concerning the primitives can be found at the author's (Dan Bernstein) website found [here](https://cr.yp.to/djb.html).  And of course, it is also a good idea to review the GoLang crypto library which has been employed by 'age'.  That lib can be found [here](https://pkg.go.dev/golang.org/x/crypto) and [here](https://golang.org/pkg/crypto/).

**And last**, in terms of security review, be aware that 'age' is **(a)** provided free of charge; **(b)** intended to be used, reviewed, commented, etc. by the user community.  Yes _FiloSottie_ (and _Benjojo12_) dev'd this thing but it seems clear (to me anyway) that their intention is for us to exercise it and provide **meaningful** feedback as we have it.

**Comment by pznknmtb** [comment]
thank you, your reaction confirms my assumptions.
