### ISSUE TITLE
Error: unknown recipient type: "github:Benjojo"

### ISSUE THREAD

**Issue by k2l8m11n2** [FiloSottile/age#121]
## Environment

* OS: Linux
* age version: 1.0.0-beta2

## What were you trying to do

Encrypt a file to a GitHub recipient, as per the example in [the spec](https://age-encryption.org/v1).

## What happened

```
alicja@autumn:~ age -r github:Benjojo -r github:FiloSottile -a
Error: unknown recipient type: "github:Benjojo"
[ Did age not do what you expected? Could an error be more useful? Tell us: https://filippo.io/age/report ]
alicja@autumn:~
```

**Comment by FiloSottile** [comment]
`github:` recipients were dropped from the plan. 53f0ebda67901013bddf1a6bd59c946574c87d0b adds a better error message.

Instead, you can do

```
curl -O https://github.com/FiloSottile.keys
age -R FiloSottile.keys
```
