### ISSUE TITLE
Parsing error in Windows

### ISSUE THREAD

**Issue by milgradesec** [FiloSottile/age#127]
## Environment

* OS: Windows 10 1909
* age version: v1.0.0-beta2

## What were you trying to do
Decrypt an encrypted file

## What happened

```
$ age -d -i key.txt encrypted.jpg.age > original.jpg
Error: failed to read header: parsing age header: unexpected intro: "age-encryption.org/v1\r\n"
```

**Comment by FiloSottile** [comment]
Thanks for reporting this. How did you create encrypted.jpg.age? It looks like the line ends got mangled, and while we could tolerate it in the header, if it happens in the encrypted data it's irrecoverable.

(As a workaround, this will probably not happen if you use -a or -o.)

**Comment by milgradesec** [comment]
Created with
```
age -r age1zyg50sa3588nnn8dxtflstvp6yst9h0ywy2vlznuv2rjj8vvgckqf8qse7 test.jpg > encrypted.jpg.age
```

You are right, fixed with
```
age -r age1zyg50sa3588nnn8dxtflstvp6yst9h0ywy2vlznuv2rjj8vvgckqf8qse7 -o  encrypted.jpg.age test.jpg
```

**Comment by a-vrma** [comment]
This happens because Powershell 5 pipes (shell redirection is implemented using pipes) try to decode data as UTF-16. It is impossible to pipe binary data around.

> (As a workaround, this will probably not happen if you use -a or -o.)

This also messes up armor. Updating to Powershell 6 --- or using `Out-File` --- would fix redirecting armor.

**Comment by milgradesec** [comment]
> This happens because Powershell 5 pipes (shell redirection is implemented using pipes) try to decode data as UTF-16. It is impossible to pipe binary data around.
> 
> > (As a workaround, this will probably not happen if you use -a or -o.)
> 
> This also messes up armor. Updating to Powershell 6 --- or using `Out-File` --- would fix redirecting armor.

Not working for me on PowerShell 7.0.1

**Comment by a-vrma** [comment]
> Not working for me on PowerShell 7.0.1

Do you mean the one with armor isn't working? It works for me on PowerShell 7.0.2. Try:
```
.\age.exe -p -a .\test.txt >test.txt.pem
.\age.exe -d .\test.txt.pem
```
Works perfectly for me. Of course, I would still recommend using `-o`.

**Comment by FiloSottile** [comment]
Closing because it doesn't look like there's anything we can do about this on our side. PowerShell users need to either use armoring, which should work with CRLF line endings, or `-o`.
