### ISSUE TITLE
Support for ecdsa-sha2-nistp256 SSH public key algorithm

### ISSUE THREAD

**Issue by fzakaria** [FiloSottile/age#142]
## Environment

* OS: Linux

## What were you trying to do

> Encrypt a file with my public key using **ecdsa-sha2-nistp256**

I was following a workflow where I wanted to encrypt a secret with all public keys listed on my GitHub account -- https://github.com/fzakaria.keys
One of the keys is _ecdsa-sha2-nistp256_ which age does not seem to support.

## What happened

```
echo "hello world" | age -r "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMSpLrw3iBKaZTxtOY6E8xzekgmhqjnCKl+biR7/AxIqkB2aqK+rO3F3p2oD3SQvJJuw/ifmryq8FOjlOH1JQ6M=" -a
Error: unknown recipient type: "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMSpLrw3iBKaZTxtOY6E8xzekgmhqjnCKl+biR7/AxIqkB2aqK+rO3F3p2oD3SQvJJuw/ifmryq8FOjlOH1JQ6M="
[ Did age not do what you expected? Could an error be more useful? Tell us: https://filippo.io/age/report ]
```

**Comment by joonas-fi** [comment]
One pro about supporting P256 is that there are HSMs like the YubiKey which allow you to do ECDH inside a trusted environment, so one could do ephemeral-static ECDH for P256 (like the existing X25519 approach is using). https://github.com/go-piv/piv-go/ supports this (thanks to @tv42)

Currently there's no ubiquitous HSM (like the YubiKey) with support to Curve25519, so P256/P384 is the best we could have with hardware protection support. P256 seems to be about an order of magnitude faster, though.

**Comment by andir** [comment]
From my limited understanding of the matter you could also use the "Secure Enclave" on Mac Books to store the key material and perform operations just like https://github.com/sekey/sekey or https://github.com/maxgoedjen/secretive (and potentially many more).

**Comment by FiloSottile** [comment]
We'll offer YubiKey (PIV) support as a plugin soon, but it will not be through SSH keys, it will be a dedicated format.

Using signing keys for encryption is a risky business, and I haven't had the time to do the research on whether it would be safe with ecdsa-sha2-nistp256 keys. Remember that SSH keys are a convenience feature, but the recommended key types are age native keys.

In the meantime, the `-L` will skip unsupported ssh key types for you if you provide it a file with all the keys.

**Comment by tv42** [comment]
> We'll offer YubiKey (PIV) support as a plugin soon

@FiloSottile Can we chat about the specifics of that? My age-plugin implementation just successfully roundtripped a message with yubikey-backed crypto, tested with rage v0.5.0. I'll happily contribute this code to whatever project wants it. You may remember me as the guy who contributed the necessary support to piv-go ;)

I could really use other people's opinions on the exact protocol, like recipient-stanza. With X25519, trying to unwrap all file keys with all the identities isn't too bad, but with a yubikey it might be nice to be more targeted, to avoid e.g. needing multiple touches -- but I'm not sure about the tradeoffs of putting a (hashed, truncated, whatever) recipient public key in the stanza.

**Comment by FiloSottile** [comment]
There were a couple more requests for ecdsa-sha2-nistp256 support, but overall it doesn't look like a critical feature, and we have had enough of a hard time proving the security of RSA and EdDSA key reuse. ECDSA is barely provable as a secure signing algorithm, and I don't want to risk reusing its keys for encryption. On balance, I think this is not worth implementing.
