### ISSUE TITLE
Decryption arguments unexpectedly order dependent

### ISSUE THREAD

**Issue by igloo22225** [FiloSottile/age#160]
## Environment

* OS: Linux defiant 5.9.8-arch1-1 #1 SMP PREEMPT Tue, 10 Nov 2020 22:44:11 +0000 x86_64 GNU/Linux
* age version: 6593c56e335f20a76275373a8b1ddf51fb662ab6

## What were you trying to do
Decrypt was a file

## What happened
Decryption arguments unexpectedly order dependent

```
 igloo@defiant  ~/workf  ../git/age/age -d IMG_20201201_205126.jpg.age -i ../git/age/somekey > img.jpg
Error: too many arguments.
age accepts a single optional argument for the input file.
[ Did age not do what you expected? Could an error be more useful? Tell us: https://filippo.io/age/report ]
 ✘ igloo@defiant  ~/workf  ../git/age/age -d -i ../git/age/somekey IMG_20201201_205126.jpg.age > img.jpg 

```

**Comment by benjojo** [comment]
@str4d points out this works in rage

**Comment by FiloSottile** [comment]
We probably don't want to pull in an external flag parsing dependency, but we should detect the issue (by noticing there is a second argument that starts with `-`) and print a suggested fixed command.
