### ISSUE TITLE
Missing binaries?

### ISSUE THREAD

**Issue by thomasdn** [FiloSottile/age#164]
Not sure if this is the right place to report this as it is more of a UX problem with the web page (Github README) rather than with the 'age' tool itself.

The README states:

> On Windows, Linux, and macOS, you can use the pre-built binaries.

This links to: https://github.com/FiloSottile/age/releases

At a first glance, this page does not contain any prebuilt binaries.
It instead contains a list of release notes.
these release notes have the source code attached as an asset.

On Dec 27, 2019, one of the release notes does indeed contain more files, presumably the prebuilt binaries for this release.
However, this is a rather old release. 

I would suggest the following improvement.

Either 1) have the text below link to a page that contains only a directory listing of the prebuild binaries of the most recent versions.

> On Windows, Linux, and macOS, you can use the pre-built binaries.

or 2) have the  README itself link directly to the prebuilt binaries for the most recent versions for various OS versions. And then provide a link to historic versions as well.

Both these improvements will make it easier for new users to obtain a copy of 'age'.

**Comment by alerque** [comment]
...or not advertise binaries at all if they aren't going to be built and released upstream.

**Comment by thomasdn** [comment]
> ...or not advertise binaries at all if they aren't going to be built and released upstream.

Sure but hopefully, binaries are  going to be built and released?

**Comment by Mohammed90** [comment]
@FiloSottile, I set this up in coming weekend with goreleaser & Github Action. Any objection to such flow?

**Comment by david415** [comment]
Yes goreleaser is a great idea because it can build binaries for lots of operating systems and platforms.
