### ISSUE TITLE
[spec] format for armored files

### ISSUE THREAD

**Issue by mdlayher** [FiloSottile/age#17]
I noticed that @str4d recently implemented support for an ASCII armored file format in rage:

https://github.com/str4d/rage/commit/da923497742a2d8d3a1da5bf70fba1e17953f3f7
https://github.com/str4d/rage/commit/9e779ddfd990dd0a0e8d2d4e229d208fbf2fd900

But I don't see anything in the spec about this format currently. I assume at this point that the two of you are in touch about it (or will be soon anyway), but it'd be good to keep the spec up to date as well.

**Comment by FiloSottile** [comment]
Yup, we discussed it a few days ago, I will update the spec.

**Comment by riking** [comment]
The implementation as linked above seems to have a malleability problem - it produces different bytes on Windows and non-Windows due to line endings, so signing the resulting file is problematic.

**Comment by FiloSottile** [comment]
Haven't read the Rust code, but what I plan to do is to normalize `\r\n` to `\n` before signing. Yes it is malleable, but that's kind of the point of the armored file, if you are 8-bit clean and was non-malleability just use the default format.

**Comment by FiloSottile** [comment]
This is now documented in the spec. @str4d we changed one small thing while implementing this (sorry!): the end of file is now `--- end of file ---`, which is not ambiguous for the same reason the end of header isn't, but lets us stick to `---`.

```
This is an armored file encrypted with age-tool.com, version 1
-> X25519 Ui4uE-MN35glMIYAAKXRtN1vqy0Jgpqzylf5FOknOTQ
2trkIGCy9wqlLx_z5eCd_Azjx6s3buQSC6qX5ofKayk
--- HjRoKlzo9ntvaByD52rH7kSIvxjvEXGDeY9bTKU5m5c
imFW2iNkNj2geOEyprUzQraNi1yqd9QGSTCkhztMBScezBZtlEDs_x8X
Ji7g4H3G62UWjTOhjXOUp-nsgfDDMK5H
--- end of file ---
```

**Comment by aaronjanse** [comment]
Hey, maybe this is off-topic or too late, but is there a reason the spec hard-wraps at 56 columns instead of allowing the file/data viewer to soft-wrap?

The salt pack format simply uses spaces every 15 characters, which wraps much more nicely on various screen sizes, as shown on their website: https://saltpack.org/

Thanks for your work, and I look forward to using `age`!

**Comment by FiloSottile** [comment]
@aaronjanse Hey, I'm trying to move spec discussions to the mailing list. Can you bring it up in this topic? https://groups.google.com/d/topic/age-dev/nNSCbk6OB9w/discussion
