### ISSUE TITLE
[spec] clarifications on HTTP hyperlink recipients in CLI

### ISSUE THREAD

**Issue by mdlayher** [FiloSottile/age#18]
I was retooling my website a bit today and also set up https://mdlayher.com/.well-known/age.keys while I was at it. This motivated me to play around and add support for keys residing at a HTTP hyperlink, per the spec.

I've got that code mostly ready whenever you're open to more contributions, but I have a few questions I'd like clarification on:

1) Is it ever reasonable to accept a plaintext HTTP URL for recipients? Since it's trivial to get proper TLS up and running these days, and sending a message to someone whose key you grabbed over plaintext HTTP seems totally insane, I personally am a strong no on this one.

2) What should happen if a server's TLS certificate is invalid or expired? Should a flag like curl's `-k/--insecure` exist?

3) How do you feel about using a domain with no path to mean "use the well-known path"? For example, https://mdlayher.com would expand to https://mdlayher.com/.well-known/age.keys. Maybe a trailing slash could be permitted too.

Thanks again! Looking forward to more Twitch streams in the future!

**Comment by str4d** [comment]
:one: In `rage` I explicitly match on `https://` to detect a URL argument, and have no plans to support plaintext HTTP.

:two: It depends on what properties of TLS certificates we (or more precisely, our users) are relying on. An invalid or expired cert is effectively no different from an authentication point of view to plaintext HTTP, but it does still encrypt the keys in transit and prevents MitMing.

From a UX perspective, encrypting to a URL implies encrypting to the identity associated with that URL. It's debatable whether any TLS certificates provide a good notion of identity-binding, but assuming that domain validation is "sufficient", it seems to me like we should lean towards "fail-closed and require user to request out-of-band that URL be fixed", given the overall intent of confidentiality.

:three: I decided not to implement this originally in `rage`, but I'm open to doing so as long as there is good documentation ensuring it is well-known :drum: :bell:

**Comment by mdlayher** [comment]
Thanks for the input, @str4d. I agree with you on all points.

**Comment by FiloSottile** [comment]
Yup, those are good questions. I agree on requiring HTTPS, and not having an `--insecure` flag (you can always curl the file down and then use it if you really want).

On 3️⃣, it's maybe a little too magic. Let's not do it for now.

**Comment by FiloSottile** [comment]
Updated the spec. Note that HTTPS recipient lists are not recursive (so they can't link to other HTTPS recipients, nor to files of course) just like file recipient lists are not recursive.

Once the spec moves to a proper man page I'll specify the format better, but it's the same as private key files: all lines must be recipients, empty, or `#` comments.

**Comment by FiloSottile** [comment]
(Let's move further spec discussions to the mailing list. https://groups.google.com/d/forum/age-dev)
