### ISSUE TITLE
Use pinentry if available

### ISSUE THREAD

**Issue by y0ast** [FiloSottile/age#182]
rage has `pinentry` support: https://github.com/str4d/rage/pull/64

It would be great if `age` could have it too.

From yubikey-agent it seems that it can be done using: github.com/gopasspw/gopass/pkg/pinentry

https://github.com/FiloSottile/yubikey-agent/blob/4998d8c3d76cbfa97fd1af2953d8eea36ae290e8/main.go

**Comment by FiloSottile** [comment]
I've decided we won't provide alternative password input methods in cmd/age, but we'll ship them all in a separate plugin, like sshpass. I'll make sure to support pinentry there, and I'll update discussion #256 when it's ready. See https://github.com/FiloSottile/age/discussions/256#discussioncomment-2638232 for a bit more details.

**Comment by FiloSottile** [comment]
The plugin is done, although it doesn't support pinentry. See https://github.com/FiloSottile/age/discussions/256#discussioncomment-15334934 for usage and for how to build a pinentry plugin.
