### ISSUE TITLE
Packaging: Add age to Chocolatey repository [help needed]

### ISSUE THREAD

**Issue by vaporwave9** [FiloSottile/age#190]
I am currently working with aquacash5 on getting magic-wormhole to the Community Package Repository of Chocolatey.org

Since you provide standalone builds for Windows it would be trivial enough to package these. As per spec the build process are a few powershell oneliners i.e. package, push etc. and providing one XML file with basic data like version number.

A working example of packaging binaries can be seen here:
https://github.com/aquacash5/magic-wormhole-exe/issues/1
Multiple binaries can be packaged in the same fashion and will get automatically shimmed by Chocolatey!

Why:
You provide windows binaries of age and your usage of magic-wormhole gave me the idea to package age as well.

Q:
Would you want to embrace the Windows community further and make age-encryption available through package repositories for the Windows world, that add age to PATH automatically for ease of installation, updating and daily usage?

Who:
Wants to maintain said repo, provided if we want to go that route?

Looking forward to other people wanting to help with this. I'd be happy to see more Go lang and Python CLI programs to enter the Windows ecosystem and more people adopting age in the hope it may become a standard or at least popular alternative for file encryption.

Cheers!

Edit:
https://chocolatey.org/docs/create-packages
https://docs.chocolatey.org/en-us/create/commands/push

**Comment by FiloSottile** [comment]
Hi! I am happy to help however I can with packaging, but I try to avoid maintaining the packages themselves for platforms I don't use, simply because I can't actively test and dogfood them.

**Comment by vaporwave9** [comment]
I could try maintain it, there are also mechanisms for the owner of a software to regain control over a package at any given time:

https://chocolatey.org/courses/creating-chocolatey-packages/package-maintainer-handover
https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process#i-want-to-take-overhelp-with-package-maintenance-for-my-software

For now I will see how pushing magic-wormhole to Chocolatey goes with the help of aquacash5 and adapt the new skills to age. Should someone more skilled and experienced feel the need to take over, I can step down any time.

But I am happy you seem to be okay with this if someone takes care of the extra work!

**Comment by FiloSottile** [comment]
You are free to make all the copies you want, you just need to copy the license along with it. This is true of most open source projects and licenses.

The copyright owner is the one that grants the license, if you look closely you'll see there is a line like that in every LICENSE file out there. There's nothing special about this one just because it happens to say Google :)

**Comment by vaporwave9** [comment]
It is done!
https://chocolatey.org/packages/age.portable
```
choco install age.portable --pre 
```
The ```--pre``` flag is required for pre-releases whilst still in beta and will automatically be dropped in stable.

This also affects search for now, as pre-releases must be allowed, but will change as well:

![grafik](https://user-images.githubusercontent.com/64961250/108729592-fd14b100-752a-11eb-9922-0a9e40ad865d.png)

**Comment by vaporwave9** [comment]
Updated:
https://chocolatey.org/packages/age.portable/1.0.0-rc1
Looking forward to stable when you feel comfortable enough that you can push.
