### ISSUE TITLE
Graphics design: A logo for 'age'?

### ISSUE THREAD

**Issue by vaporwave9** [FiloSottile/age#192]
![shinto_torii_fix](https://user-images.githubusercontent.com/64961250/108771495-0c602280-755c-11eb-9d2e-da4ccbc20b8d.png)

Some package repositories wish that a logo is provided for software. Whilst it is not demanded, it can help users to recognize the package they want.

Age introduces itself as being:
> called “age”, which might be an acronym for Actually Good Encryption,
> and it’s pronounced like the Japanese 上げ (with a hard g).
>

Based on its strong Japanese reference I chose to propose a very simplistic logo design:
* a Torii with a a keyhole at its center
> a traditional Japanese gate most commonly found at the entrance of or within a Shinto shrine,
>where it symbolically marks the transition from the mundane to the sacred
> general symbol for security

CC0 - public domain SVG were used to render the above PNG.
https://commons.wikimedia.org/wiki/File:Shinto_torii_icon_vermillion.svg
https://commons.wikimedia.org/wiki/File:Office-protection-shackle-keyhole.svg

Any other logo may be suggested or this idea may be completely scrapped. This is merely the attempt to encourage an actual graphics designer to come up with something we can use, if a logo is wanted.

Examples of good design:
https://github.com/Tox
https://github.com/DNSCrypt/dnscrypt-proxy/blob/master/README.md

**Comment by tunnckoCore** [comment]
The Tox one is cool idea.

Probably some black square with rounded corners, and inside instead of keylock, to be the Torii in white, and in the middle of it again in black a keyhole.

**Comment by vaporwave9** [comment]
![torii_min](https://user-images.githubusercontent.com/64961250/109322798-05cef500-7853-11eb-856a-ac8bac55ff48.png)
![torii_min_2](https://user-images.githubusercontent.com/64961250/109322813-09627c00-7853-11eb-9d57-27015603b3ad.png)

>black square with rounded corners, and inside instead of keylock, to be the Torii in white, and in the middle of it again in black a keyhole
>

Gotcha!

**Comment by tunnckoCore** [comment]
EXACTLY! :laughing:

Love it. :rocket:
