### ISSUE TITLE
Brew installation overwrite go local go installation

### ISSUE THREAD

**Issue by yulrizka** [FiloSottile/age#194]
## Environment

* OS: OSX Catalina
* age version: v1.0.0-beta6

## What were you trying to do

Install age view homebrew

## What happened

It replaced my installed goversion (go1.16) to (go.1.15.2)

I installed using the installer from golang website. After Installation it downgrade my golang. 
It seems that `/usr/local/Cellar` was put in front of my local go package. So when it installed go
it picked that one up instead the one that the package installed (/usr/local/go)

Maybe there is a better alternatives for the go installation?

**Comment by FiloSottile** [comment]
Installing age with Homebrew will install Go with Homebrew as well, as it's needed to build age.

Your options are using `brew unlink go` to remove Homebrew's Go from `/usr/local/bin`, putting the manual installation of Go (`/usr/local/go/bin`) in front of the PATH, or upgrading the Homebrew Go (which is [currently 1.16](https://formulae.brew.sh/formula/go#default), so not sure why you got 1.15.2).

This is not something we can do anything on our side.
