### ISSUE TITLE
Can't compile: undefined: ssh.PassphraseNeededError

### ISSUE THREAD

**Issue by Fastidious** [FiloSottile/age#21]
Trying to build it, I get:
```
dreadnought:~ fastidious$ go get github.com/FiloSottile/age/cmd/age/
# github.com/FiloSottile/age/cmd/age
go/src/github.com/FiloSottile/age/cmd/age/parse.go:86:25: undefined: ssh.PassphraseNeededError
```
Go version `go1.13.1 darwin/amd64`.

**Comment by magical** [comment]
There should have been some output where `go build` downloads Filo's fork of x/crypto. Did you disable module support or something?

**Comment by Fastidious** [comment]
@magical since the last time I compiled it (three weeks ago, or so) there hasn't been any changes on my system, nor I have disabled anything (I wouldn't know how to disable module support).

**Comment by sigmarelax** [comment]
I'm getting the same error. Been getting around it by using 'go run' from the root dir of the project. ie:
`cd ~/go/src/github.com/FiloSottile/age && go run ./cmd/age`

**Comment by FiloSottile** [comment]
Until we can drop the `replace` in the `go.mod`, this needs to be the main module when building. This is part of the unfortunate UX of installing go binaries with modules. See golang/go#30515.

In practice, it means you need to `cd` into the repo to do anything.

```
$ git clone https://github.com/FiloSottile/age
$ cd age && go install ./cmd/age
```
