### ISSUE TITLE
CLI user interface?

### ISSUE THREAD

**Issue by fd0** [FiloSottile/age#22]
Hi,

thanks a lot for writing age, I'm really looking forward to using it!

Is the CLI user interface already fixed, or are you open to a discussion about it?

I'd like to propose the following:

 * Add subcommands (like `git` and `go`):
   * `age encrypt` (maybe default?)
   * `age decrypt`
   * `age generate`
 * Use the double-dash syntax (maybe with `pflag`?) to distinguish between short and long options

With these proposed modifications, the commands from the spec would look as follows:

    $ age generate > key.txt

    $ echo "_o/" | age encrypt pubkey:98W5ph53zfPGOzEOH-fMojQ4jUY7VLEmtmozREqnw4I > hello.txt.age

    $ age decrypt key.txt < hello.txt.age
    _o/

    $ tar cv ~/xxx | age encrypt github:Benjojo github:FiloSottile | nc 192.0.2.0 1234

    $ echo "_o/" | age encrypt -o hello.age pubkey:98W5ph53zfPGOzEOH-fMojQ4jUY7VLEmtmozREqnw4I

    $ age encrypt -i hello.txt -o hello.txt.age -p
    Type passphrase:

The upsides are:
 * Adding subcommands would avoid ambiguities by forcing the user to be explicit about the intended operation. With `gpg`, I'm never entirely sure if it is in encrypt or decrypt or signing or whatever mode. In addition, this makes it easy to distinguish between a command (`generate`, `encrypt`) and an option (`--output`, `--recipient` etc.).
 * Make it clear to the user that subcommands are mutually exclusive: `age encrypt generate -o foo` is clearly wrong, but `age -encrypt -generate -o foo` is not so clear in my opinion.

For the flag parsing, I really like http://github.com/spf13/pflag, we could also implement that ourselves. Subcommands can be implemented without an external dependency. What's your take on dependencies for `age`? Stdlib only?

What do you think? I'm willing to help set this up if you're up for it, if not please just close this issue and carry on. Thanks!

**Comment by FiloSottile** [comment]
About long options, I always planned to provide long versions of all short options except `-i` and `-o`. The standard flags package already supports double dashes if that's what you prefer, so I don't see the need to use a third party package: the only difference would be that it would make it possible to combine multiple short options, which I think is an anti-pattern. We shouldn't have that many options to begin with!

I am not a fan of sub-commands, they are necessary when you have a sprawling CLI, but we shouldn't! They reduce discoverability and make commands more verbose. I understand the frustration with not knowing what mode gpg is in, but we really only have two: encrypt and decrypt. Maybe generate should even be a separate binary, `age-keygen`?

I do think we need to change the CLI a bit though. "All arguments are recipients or keys" was clever, but is not usable: people will pass inputs as arguments all the time, and with `-i` you have to put the key after the input. I'm thinking we just drop arguments entirely, and introduce `-r/-recipient` and `-k/-key`. Or... we take a single optional argument as input, and use `-i/-identity` for decryption, matching SSH.

```
$ age-keygen > key.txt

$ echo "_o/" | age -r pubkey:98W5ph53zfPGOzEOH-fMojQ4jUY7VLEmtmozREqnw4I > hello.txt.age

$ age -d -i key.txt hello.txt.age
_o/

$ tar cv ~/xxx | age -r github:Benjojo -r github:FiloSottile | nc 192.0.2.0 1234

$ echo "_o/" | age -o hello.age -r pubkey:98W5ph53zfPGOzEOH-fMojQ4jUY7VLEmtmozREqnw4I

$ age -o hello.txt.age -p hello.txt
Type passphrase:
```

**Comment by str4d** [comment]
A separate keygen binary is probably a good idea in order to simplify the UX.

I like moving from positional arguments to repeated `-r recipient` (it would similarly improve the `rage` UX). I did wonder for a moment whether it would make recipient expansion in the CLI harder (i.e. `cat foo | age $(fetch_recipients from somewhere) >bar` would need to interpolate `-r`), but I think it's probably better to just direct this kind of use-case towards storing the recipients in an intermediate file and then using `cat foo | age -r recipients.txt >bar` instead.

I'm ambivalent about `-k` vs `-i`. If we did have a single positional argument as input, then should we support the somewhat-common convention of mapping the filename `-` to stdin? Incidentally, I see that `gpg` (at least according to its manpage) requires passing `-o -` in order to write to stdout.

**Comment by FiloSottile** [comment]
> I'm ambivalent about `-k` vs `-i`. If we did have a single positional argument as input, then should we support the somewhat-common convention of mapping the filename `-` to stdin? Incidentally, I see that `gpg` (at least according to its manpage) requires passing `-o -` in order to write to stdout.

Yeah, let's honor the mapping. I want it to be easy to pipe input and output, so stdin and stdout should stay the defaults if no argument or `-o` is specified. We can refuse to spew binary to stdout unless overridden with `-o -`, though.

**Comment by FiloSottile** [comment]
Done! I'll update the spec later.

**Comment by fd0** [comment]
Great, thanks!
