### ISSUE TITLE
Consider goreleaser for building releases

### ISSUE THREAD

**Issue by twpayne** [FiloSottile/age#25]
[goreleaser](https://goreleaser.com/) makes it really easy to build Go binaries for multiple platforms, including generating `.rpm`s, `.deb`s, tarballs, zip files, Homebrew formulae, Snapcrafts, Scoops, and the like. It would be a great fit for age.

Let me know if you'd like a PR that adds this. Thanks to @joemiller who contributed this to chezmoi in https://github.com/twpayne/chezmoi/pull/33 - I'd like to pay the contribution forward.

**Comment by emaste** [comment]
It looks like there's not yet FreeBSD support in [goreleaser](https://goreleaser.com) :(

**Comment by twpayne** [comment]
@emaste Goreleaser does support FreeBSD, and OpenBSD. It supports all OSs that Go can cross-compile to.

**Comment by whalehub** [comment]
@FiloSottile Any thoughts on this?
