### ISSUE TITLE
Age doesn't ask for passphrase when dealing with encrypted identity file

### ISSUE THREAD

**Issue by ankit255** [FiloSottile/age#282]
The below example is from the official README:
```
$ age-keygen | age -p > key.age
Public key: age1yhm4gctwfmrpz87tdslm550wrx6m79y9f2hdzt0lndjnehwj0ukqrjpyx5
Enter passphrase (leave empty to autogenerate a secure one):
Using the autogenerated passphrase "hip-roast-boring-snake-mention-east-wasp-honey-input-actress".
$ age -r age1yhm4gctwfmrpz87tdslm550wrx6m79y9f2hdzt0lndjnehwj0ukqrjpyx5 secrets.txt > secrets.txt.age
$ age -d -i key.age secrets.txt.age > secrets.txt
Enter passphrase for identity file "key.age":
```

This fails on my system and age doesn't ask for passphrase for the identity file. Instead the following error is produced:
`
Error reading "key.age": failed to read "key.age": error at line 1: malformed secret key: separator '1' at invalid position: pos=20, len=21
`

My system is a Macbook Pro with Apple M1 running MacOS Big Sur 11.4 and Age version 1.0.0-rc2

**Comment by FiloSottile** [comment]
This feature is new in v1.0.0-rc.3. Please update and let me know if it still doesn’t work.

**Comment by ankit255** [comment]
Ok. Waiting for homebrew to update to rc3...
