### ISSUE TITLE
cmd/age: support for SSH identities and recipients

### ISSUE THREAD

**Issue by mdlayher** [FiloSottile/age#3]
I started poking around at this last night and before work this morning and should have a usable patch at some point after work tonight. Will send a PR.

**Comment by FiloSottile** [comment]
Thanks, I'll try not to conflict with that, but I should mention that this week might not be a good time to develop PRs, because I assume I will change a lot of things as I add bits and pieces and reconsider the decisions made over the weekend.

**Comment by mdlayher** [comment]
Good to know, no worries either way. I'll hold off after this patch then.
