### ISSUE TITLE
Option --encrypt  does not work - causes usage exit

### ISSUE THREAD

**Issue by jimmyb-gh** [FiloSottile/age#324]
FreeBSD jpbsd 13.0-RELEASE-p4 FreeBSD 13.0-RELEASE-p4 #0: Tue Aug 24 07:33:27 UTC 2021     root@amd64-builder.daemonology.net:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64

* age version:
[jpb@jpbsd:~/.mykeep]$ age --version
(devel)

## What were you trying to do 

Encrypt a file using a passphrase.

## What happened
Error exit.

Looks like the '--encrypt'  option is not recognized.

```
jpb@jpbsd:~]$ age --encrypt --passphrase --armor -o hosts.asc hosts
flag provided but not defined: -encrypt
Usage:
    age (-r RECIPIENT | -R PATH)... [--armor] [-o OUTPUT] [INPUT]
...
error exit

[jpb@jpbsd:~]$ echo $?
2

```

This is possibly a FreeBSD portage problem.  Not sure...

Jim Brown,
jpb@jimby.name

**Comment by FiloSottile** [comment]
Yeah, the FreeBSD port is way behind at v1.0.0-beta6, which didn't have `-e` at all. Also, they should be adding the ldflags to bake the version into the binary, so this kind of confusion is easier to debug.

https://cgit.freebsd.org/ports/tree/security/age/Makefile

Mind reporting it to them? Thank you!

**Comment by jimmyb-gh** [comment]
Done.
