### ISSUE TITLE
Don't take passphrase via CLI param

### ISSUE THREAD

**Issue by est31** [FiloSottile/age#37]
On unix systems, each unprivileged user has read access to the CLI params of all processes running on the system. Thus, CLI params are to be considered public information and are to be deemed unfit as a means to transport secret data like passphrases. age shouldn't support a mode that takes the passphrase as CLI params. Safer alternatives are manual prompting as well as environment variables.

**Comment by str4d** [comment]
This is a misunderstanding of the usage documentation. `-p` is a flag that indicates a file should be encrypted with a passphrase. It does not take the passphrase as an argument; the user is manually prompted. Is there a way to make this clearer in the usage documentation generated by the go package handling CLI options?

**Comment by est31** [comment]
Oh sorry you are right of course. Yeah I derived my assumption about the behaviour from the usage documentation without looking into source code. The source code confirms what you state. Thanks for clearing this up!
