### ISSUE TITLE
website: your connection is not private

### ISSUE THREAD

**Issue by georgevreilly** [FiloSottile/age#370]
## Environment

* OS: n/a
* age version: n/a

## What were you trying to do

Visit https://age-encryption.org/

## What happened

<img width="822" alt="Screen Shot 2021-12-05 at 13 02 46" src="https://user-images.githubusercontent.com/34297/144763899-739d12b0-6a19-45b7-856f-349f19b59885.png">

```text
Your connection is not private
Attackers might be trying to steal your information from age-encryption.org (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_COMMON_NAME_INVALID
To get Chrome’s highest level of security, turn on enhanced protection
age-encryption.org normally uses encryption to protect your information. When Chrome tried to connect to age-encryption.org this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be age-encryption.org, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Chrome stopped the connection before any data was exchanged.

You cannot visit age-encryption.org right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.
```

**Comment by FiloSottile** [comment]
Your network is MitM'd, probably by some "security" product that breaks HTTPS for sites on its blocklist in a counter-productive attempt to show a "we just kept you safe!" page. Moreover, the vendor of that product has flagged age-encryption.org as malware because of two layers of incompetence: thinking that a library used by one ransomware campaign once should be universally blocked, and thinking that blocking a website with only a redirect to GitHub does anything against malware that uses the library (which obviously does not connect to age-encryption.org at runtime).

If you have any power over the choice of vendor, I invite you to consider this performance in its selection.

In any case, please load the page with `curl -k` and let us know who we should try to reach out to.

**Comment by georgevreilly** [comment]
CenturyLink is providing my Internet connection.

```
curl -k -v https://age-encryption.org/
*   Trying 213.188.195.45:443...
* Connected to age-encryption.org (213.188.195.45) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=California; L=Santa Clara; O=McAfee, Inc.; OU=Consumer; CN=*.safezone.mcafee.com
*  start date: Aug 27 00:00:00 2021 GMT
*  expire date: Aug 27 23:59:59 2022 GMT
*  issuer: C=US; ST=CA; L=Santa Clara; O=McAfee, Inc.; CN=McAfee OV SSL CA 2
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: age-encryption.org
> User-Agent: curl/7.77.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< Date: Mon, 06 Dec 2021 00:18:54 GMT
< Server: SHP
< Referrer-Policy: no-referrer
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: DENY
< Content-Security-Policy: default-src 'self' http://shgw.router:8080 stats.g.doubleclick.net www.google-analytics.com analyticsdcs.ccs.mcafee.com *.mcafee.com https://websdk.moengage.com  https://inapps.moengage.com  https://cdn.moengage.com; script-src * 'unsafe-inline' 'unsafe-eval'; style-src * 'unsafe-inline' 'unsafe-eval'
< Cache-Control: no-store, no-cache, must-revalidate, max-age=0
< Cache-Control: post-check=0, pre-check=0
< Pragma: no-cache
< Location: http://blockpg-dock.safezone.mcafee.com/blockpage/redirect/?ctxt=Kzd5WVBCL0JWS0lTS0c0YXhxNWdKMjlLaWVrVDNEUkUzU1FzODFUcnMyc0xFQTFlUVpPV0VFMnVJMklpRlRVeUdhR1BGTWIxR3RGbmgwaWdHdHZP&ts=1638749934
< Content-Length: 0
< Connection: close
< Content-Type: text/html; charset=UTF-8
<
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, close notify (256):
```

**Comment by FiloSottile** [comment]
CenturyLink does this MitM as a "feature" called Secure WiFi, operated by McAfee.
https://www.centurylink.com/home/help/internet/secure-wifi.html

For most sites, it will train users to click though HTTPS warnings, making them less secure. age-encryption.org is HSTS preloaded into browsers so that such an insecure bypass is not possible.

I reported the ludicrous false positive. They say they will fix it in two days, if at all. Not holding my breath, but that's all I can do about it. Still, thank you for reporting it. It looks like you need to contact support if you wish to turn this off.

**Comment by supersat** [comment]
It gets worse than that. They specifically encourage you to turn off new security features in Chromium. 

![image](https://user-images.githubusercontent.com/1396229/144771881-98ff40ec-bf70-46a6-8d81-c72ee04c3684.png)

Chrome is tracking this with https://bugs.chromium.org/p/chromium/issues/detail?id=1273300

**Comment by neelchauhan** [comment]
I also have CenturyLink, but use an OPNsense firewall. IMHO get your own router with CenturyLink.

If you have DSL, bridge your modem and use a router supporting PPPoE.

if you have Fiber (like me), get a router supporting PPPoE-over-VLAN and tag VLAN 201, or use pfSense/OPNsense.

If you "own" the CenturyLink modem/router, keep it in case you need tech support (common on fiber), and bridge it on DSL, or put it in a box on fiber. If you are "leasing" the CenturyLink modem/router and have DSL, get a cheap C1100T or something on eBay and bridge that to your new router.

Most routers should work fine, but one brand to avoid is Eero, unless you use Eero in bridge mode to say pfSense or OpenWrt as Eeros don't support PPPoE.

**Comment by aarongable** [comment]
For posterity: It appears that you can also disable this behavior by logging in to your centurylink router (the usual 192.168.0.1; username and password printed on the router if you haven't changed them), navigated to Advanced Setup --> Security --> Cyber Security, selecting "Disable Modem Security until I Turn Back to On" (sic), and applying the settings change.

It's very unclear what else this disables, if anything, and there's nothing on the page directly associating it with centurylink's "Secure WiFi" "product", but it did immediately remove the attempts to MitM my connection.

**Comment by andrewrk** [comment]
Thank you so much @aarongable! I was going nuts and this method solved the problem for me. If CenturyLink had any competitors I would switch immediately but alas it is a monopoly.

**Comment by Rican7** [comment]
Oh **wooooww**. Thank you SO much for this thread, and especially the details about CenturyLink doing this (@FiloSottile) and the ways to disable it (@aarongable).

I've been running into weird behaviors on [Threads](https://www.threads.net/) where suddenly media wouldn't load, and lately more specifically with opening Threads links (via https://l.threads.net/) causing a `NET::ERR_CERT_COMMON_NAME_INVALID` "Privacy error" in Chrome, and it's been bugging me for a few days, but I wasn't able to find anything until I searched for just the right combination of things on Google (query was `l.threads.net McAfee OV SSL CA 2 NET::ERR_CERT_COMMON_NAME_INVALID`).

<details>
<summary>It wasn't until I found this thread that I ran a similar `curl -k -v https://l.threads.net/` to find that I was also being MITM'd by my ISP (CenturyLink).</summary>
<pre><code>$ curl -k -v https://l.threads.net/
*   Trying 57.144.104.192:443...
* Connected to l.threads.net (57.144.104.192) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=California; O=McAfee, Inc.; CN=*.safezone.mcafee.com
*  start date: Jun 22 00:00:00 2023 GMT
*  expire date: Jun 21 23:59:59 2024 GMT
*  issuer: C=US; ST=CA; L=Santa Clara; O=McAfee, Inc.; CN=McAfee OV SSL CA 2
*  SSL certificate verify result: self-signed certificate in certificate chain (19), continuing anyway.
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> GET / HTTP/1.1
> Host: l.threads.net
> User-Agent: curl/7.81.0
> Accept: */*
>
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< Date: Wed, 24 Jan 2024 00:55:32 GMT
< Server: SHP
< Referrer-Policy: no-referrer
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: DENY
< Content-Security-Policy: default-src 'self' http://shgw.router:8080 stats.g.doubleclick.net www.google-analytics.com analyticsdcs.ccs.mcafee.com *.mcafee.com https://websdk.moengage.com  https://inapps.moengage.com  https://cdn.moengage.com; script-src * 'unsafe-inline' 'unsafe-eval'; style-src * 'unsafe-inline' 'unsafe-eval'
< Cache-Control: no-store, no-cache, must-revalidate, max-age=0
< Cache-Control: post-check=0, pre-check=0
< Pragma: no-cache
< Location: http://blockpg-dock.safezone.mcafee.com/blockpage/redirect/?ctxt=Kzd5WVBCL0JWS0lTS0c0YXhxNWdKMjlLaEtBQ21TTlAzekltclU3bnFGa0tYVk1iZU4rV0JsN25ZalJyQmlNaFd1S2JIc0wwSHRwaXpnPT0=&ts=1706057732
< Content-Length: 0
< Connection: close
< Content-Type: text/html; charset=UTF-8
<
* Closing connection 0
* TLSv1.2 (IN), TLS header, Unknown (21):
* TLSv1.2 (IN), TLS alert, close notify (256):
* TLSv1.2 (OUT), TLS header, Unknown (21):
* TLSv1.2 (OUT), TLS alert, close notify (256):
</code></pre>
</details> 

Ew. I hate this.

Luckily, there's a way to disable it in my modem's configuration, as @aarongable mentioned, but the setting is cryptic and has **0** explanation for what the feature does or the implications of toggling it on or off. What a horrible experience.

![image](https://github.com/FiloSottile/age/assets/742384/9bea9f1d-841b-4417-a990-d8295d891986)

I'm leaving this comment here to hopefully make the specific case I ran into more easy of a find on Google, and in case someone else runs into the exact same problem.

Thanks again, y'all!
