### ISSUE TITLE
Signing and signature validation 

### ISSUE THREAD

**Issue by orsinium** [FiloSottile/age#38]
As I understand, the project is "pgp killer" that sounds incredibly cool.

1. Is it possible to sign a text and validate signature?
2. Is it possible to use ssh key pair for it?

Sorry if I missed something from the readme.

**Comment by ovalseven8** [comment]
Signing is out of scope for `age` (see https://age-encryption.org/v1):
> Any kind of signing (which is not a tooling problem, but a trust and key distribution problem, and to the extent that tools matter you should just use signify/minisign, and for keys we should probably use SSH ones)

**Comment by str4d** [comment]
It is however possible to use SSH keypairs with age - specifically, age can encrypt to ssh-rsa and ssh-ed25519 keypairs for (limited) backwards compatibility.

**Comment by iger** [comment]
Is there a recommended way to have streamed authenticated decryption?

**Comment by orsinium** [comment]
#51 has a deeper coverage of the problem statement. Let's keep the discussion there. Thank you all for your help!
