### ISSUE TITLE
UX: Confirm passphrase

### ISSUE THREAD

**Issue by nunocastromartins** [FiloSottile/age#39]
## What were you trying to do

Encrypting a file with a passphrase.

## What happened

Passphrase was only asked once (no confirmation was asked).

While asking for a confirmation of the passphrase is not foolproof, it may help prevent typos when encrypting files (the user may assume that everything went fine and delete the unencrypted file, only to later find out that the file had been encrypted with a wrong passphrase).

**Comment by FiloSottile** [comment]
Yep, good idea, thank you!
