### ISSUE TITLE
Installation instructions using `go` don't work on Debian 11.

### ISSUE THREAD

**Issue by vext01** [FiloSottile/age#399]
## Environment

* OS: Debian 11
* age version: -

## What were you trying to do

Install via go, as per the README:

```
go install filippo.io/age/cmd/...@latest
```

## What happened

```
$ go install filippo.io/age/cmd/...@latest
go: warning: "filippo.io/age/cmd/...@latest" matched no packages
```

**Comment by vext01** [comment]
Should it be `go get ...`

**Comment by FiloSottile** [comment]
That's correct, age requires a supported version of Go to build.
