### ISSUE TITLE
Use age-encryption.org for brew tap

### ISSUE THREAD

**Issue by sandstrom** [FiloSottile/age#40]
Awesome library!

Two thoughts:

- How about using https://age-encryption.org for the brew taps?

- You could also use the Github verification system to "prove" that you control age-encryption.org, making it easier to trust that it's the right one.

**Comment by FiloSottile** [comment]
I want to keep a distinction between the format, which is age-encryption.org, and the Go implementations, which is filippo.io/age. There are other age-encryption.org implementations already, like github.com/str4d/rage. Anyway, I hope we'll get into homebrew-core soon enough and the tap can go away.

**Comment by sandstrom** [comment]
Makes sense! Thanks for a great standard/lib! 😄
