### ISSUE TITLE
Output file is always created, even if an error happens

### ISSUE THREAD

**Issue by notramo** [FiloSottile/age#411]
When there is an error, e.g. pressing Ctrl+C in password prompt, or something other, the output file is created as an empty file.

**Comment by FiloSottile** [comment]
That's weird, we had fixed this in 97b6569a66c5fa08ab2b79620bea5501d994c3a7.

Can you follow the issue template and share the age version and the command line you used?

**Comment by notramo** [comment]
It's `1.0.0`.  I can't reproduce now, but it happened with this version. I don't know the exact parameters that can reproduce it. Maybe terminal I/O was messed up somehow? It was in password mode.

**Comment by FiloSottile** [comment]
If you used shell redirection, like `age -p input > output.age`, then the shell created the file and there's nothing age can do about it. If you used `-o output` and exited during the password prompt, then it's a bug, but I can't reproduce it. If you can, please post a transcript and I'll reopen the issue!
