### ISSUE TITLE
Question: What's the maximum file size to encrypt/decrypt

### ISSUE THREAD

**Issue by ovalseven8** [FiloSottile/age#44]
I'm a simple developer with very little crypto knowledge, so I'm trying to understand how `age` works internally.

`age` is using authenticated encryption and is using streaming/chunking so that you can encrypt/decrypt large files without having to put the whole file into the RAM.

The chunk size is 64 KiB, the encrypted chunk size is `encChunkSize  = ChunkSize + poly1305.TagSize`, what's 65 KiB + 16 KiB = 81 KiB.

I've read that we have to include the order of the chunk in the encrypted chunk so that you cannot change the ciphertext (mix up encrypted chunks).

How I read the `age` documentation, the Poly1305 authenticator (16 bytes) is a random nonce. Also, in the STREAM algorithm, a 11 byte nonce and a 1 byte last block flag is used.

As far as I understand, the 11 byte nonce is for indicating the order of the chunk, with chunk1, the 11 byte nonce is 1, with chunk2, the 11 byte nonce is 2, etc.

So, does this mean that the theoretical max. size of file `age` can handle is 2^(11*8)*64 KiB?

Sorry in case it does not make any sense, I'm just trying to understand. :smile:

**Comment by FiloSottile** [comment]
> The chunk size is 64 KiB, the encrypted chunk size is `encChunkSize = ChunkSize + poly1305.TagSize`, what's 65 KiB + 16 KiB = 81 KiB.

`poly1305.TagSize` is 16 bytes, not KiB.

> How I read the `age` documentation, the Poly1305 authenticator (16 bytes) is a random nonce.

The Poly1305 authenticator is a MAC tag, not a nonce. The nonce is the counter, as you say below.

> So, does this mean that the theoretical max. size of file `age` can handle is 2^(11*8)*64 KiB?

Correct, 2.028×10^13 EB (exabytes) =)
