### ISSUE TITLE
Feature request: Support for symmetric key files

### ISSUE THREAD

**Issue by Paragis** [FiloSottile/age#46]
I would like to consider the age format for some future applications, however a common requirement is the use of key files instead of passwords, especially where no user interaction is given.
The key files in these scenarios are used as symmetric keys and optionally protected by a master password. One of the application ideas is similar to a rachet with pre shared symmetric keys, where the user enters a password to access an app and decrypt the keyfiles for the session. 

Currently supported in age:
- asymmetric keys
- passwords (interactive only)

Wanted feature:
- symmetric keys

**Comment by kousu** [comment]
This is implemented now: https://github.com/FiloSottile/age#passphrases

**Comment by str4d** [comment]
Age's "one joint" is the identity/recipient format, which is designed for arbitrary extensibility, and we are working on a plugin system that will enable this extensibility to be implemented easily by third parties. It is definitely possible for someone to define an identity/recipient format that uses keyfiles for symmetric wrapping of the file key. The keyfiles themselves could also be encrypted with age in passphrase mode, as indicated above 🙂

**Comment by FiloSottile** [comment]
This is now supported, in the sense that you can encrypt to an X25519 identity file as of 732f3e8a949e6557dbabfea97eb2059d4b7a5007.

The motivation for it ended up being symmetric plugins, that don't have a meaningful identity vs recipient distinction. It makes sense to use an identity file for those for both encryption and decryption. If it's supported for plugins, why not for everything.
