### ISSUE TITLE
Age v1.1.0 fails to build with "go install"

### ISSUE THREAD

**Issue by JerryLava** [FiloSottile/age#472]
## Environment

* OS: macOS or Linux, go1.19.2 or go1.19.4
* age version: Latest checkout from git

## What were you trying to do

Attempting to install go from source using the instructions in README.md

`$ go install filippo.io/age/cmd/...@latest`

## What happened

Go doesn't get built

```
go: downloading filippo.io/age v1.1.0
go: filippo.io/age/cmd/...@latest (in filippo.io/age@v1.1.0):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

```
$ go version
go version go1.19.4 linux/amd64
```

```
$ go version
go version go1.19.2 darwin/arm64
```

**Comment by alerque** [comment]
I built the packages for Arch Linux form the source tarball using Go 1.19.4 with no trouble. Is this a Git clone vs. tarball issue?

**Comment by JerryLava** [comment]
It builds fine from the latest git checkout:

```
$ git clone https://github.com/FiloSottile/age.git
Cloning into 'age'...
cremote: Enumerating objects: 2205, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 2205 (delta 2), reused 14 (delta 2), pack-reused 2185
Receiving objects: 100% (2205/2205), 1.43 MiB | 3.87 MiB/s, done.
Resolving deltas: 100% (1288/1288), done.
$ cd age/cmd/age
$ go build
$  ./age --version
(devel)
```

**Comment by FiloSottile** [comment]
Ah, thank you, I forgot to remove the `replace` directive, which breaks `go install`, but not `go build` invoked from the source directory. I'll issue a v1.1.1.
