### ISSUE TITLE
 command '/bin/sh -c go install filippo.io/age/cmd/...@latest' returned a non-zero code: 1

### ISSUE THREAD

**Issue by kavita1205** [FiloSottile/age#488]
## Environment
Hi Team,

I am using below Dockerfile in my CICD jenkins pipeline but this docker file is failing while running line "go install filippo.io/age/cmd/...@latest" with below error message. Can someone please help me here or provide a solution over it.

Error message 
```
Step 5/5 : RUN go install filippo.io/age/cmd/...@latest
 ---> Running in 7ce425d8799b
go: downloading filippo.io/age v1.1.1
go: downloading golang.org/x/term v0.3.0
go: downloading golang.org/x/crypto v0.4.0
go: downloading filippo.io/edwards25519 v1.0.0
go: downloading golang.org/x/sys v0.3.0
//go:build comment without // +build comment
The command '/bin/sh -c go install filippo.io/age/cmd/...@latest' returned a non-zero code: 1
```
![image](https://user-images.githubusercontent.com/57555403/213197878-3c3d54f6-a54d-40ec-adf0-f63725f44140.png)

Dockerfile 
```
FROM quay.io/helmpack/chart-testing:v3.5.0
LABEL Name=ML42helmcharts Version=0.0.1

# Used to se the HELM working directory
ENV HOME=/tmp

# Install the necessary tools
RUN apk add go 
RUN go install filippo.io/age/cmd/...@latest
```
* OS:
* age version:

## What happened

```
<insert terminal transcript here>
```

**Comment by kavita1205** [comment]
@FiloSottile can you please help me here.

**Comment by git001** [comment]
Well your `chart-testing` is to old.  
https://quay.io/repository/helmpack/chart-testing?tab=tags

> FROM quay.io/helmpack/chart-testing:v3.5.0
> v3.5.0 => a year ago

Use a newer Version and the build works
> FROM quay.io/helmpack/chart-testing:v3.7.1
> v3.7.1 => 4 months ago

My suggestion is to update the components from time to time to the latest version, sometimes the update solve some issues :smile:

**Comment by kavita1205** [comment]
@git001 Thankyou for your response and it worked now. I just updated chart-testing version to v3.7.1 and it worked.

Thanks a lot once again. 🙏
