### ISSUE TITLE
Feature request: Post quantum crypto

### ISSUE THREAD

**Issue by Paragis** [FiloSottile/age#55]
Given that age aims to be the encryption tool for the future, it should include (asymmetric) crypto that will survive the expected arrival of quantum computers.

openssh already has this implemented:
> ... based on a combination of Streamlined NTRU Prime 4591^761 and X25519.
https://www.openssh.com/releasenotes.html

Alternatively the NIST Competition for post-quantum crypto is getting to the final round in summer 2020
https://en.wikipedia.org/wiki/Post-Quantum_Cryptography_Standardization

**Comment by Macil** [comment]
Do we know if the public keys for these systems are still short enough to use as command-line arguments comfortably, or would a post-quantum age need arguments that are files containing the public keys? I know some post-quantum systems have very large public keys.

**Comment by cyb3rz3us** [comment]
Given that the exchange method suggested above is still experimental, IMO this seems a bit premature for insertion into 'age' at present.
