### ISSUE TITLE
ssh connection to Github

### ISSUE THREAD

**Issue by lilyanB** [FiloSottile/age#556]
## Environment

* OS: ubuntu

## What were you trying to do

I have removed my SSH key from my old computer and also deleted it from GitHub.
On 04/03/2024, I generated a new SSH key and added it to my GitHub account.

However, the snapshot shows that this new key does not match.

Can you help me please

## What happened

An error because I'm using my new ssh key

```
You have specified the file which doesn't contain valid private key.
Your private key doesn't match your public key in GitHub. It could happen if you've changed local ssh key recently.
```

**Comment by FiloSottile** [comment]
Based on other similar issues like yours that were received in the past, most likely your problem is with the `fluencelabs/dev-rewards` project as described here: <https://github.com/fluencelabs/dev-rewards/issues/19>
