### ISSUE TITLE
identities bug

### ISSUE THREAD

**Issue by SuperUsr99** [FiloSottile/age#604]
## Environment

 OS:Artix Linux
 age version:1.2.0

## What were you trying to do
I am trying to "show" my password with passage

## What happened

age: error: reading "/home/Mylogin/.passage/identities": failed to read "/home/Mylogin/.passage/identities": error at line 4: unknown identity type

age: report unexpected or unhelpful errors at https://filippo.io/age/report

On line 4 in file identities it is:  -----BEGIN AGE ENCRYPTED FILE-----
```

passage show ОS/AppleID
age: error: reading "/home/super_me/.passage/identities": failed to read "/home/super_me/.passage/identities": error at line 4: unknown identity type
age: report unexpected or unhelpful errors at https://filippo.io/age/report

**Comment by SuperUsr99** [comment]
It happened after I added password  to  open my storage

**Comment by SuperUsr99** [comment]
Whoops, I first created the simple key and then rewrote the file with the new version of key (Key with password demand). Now my identities file looks correct. but I got other issue.

**Comment by SuperUsr99** [comment]
Ok, I reinstalled it and everything works fine.

**Comment by FiloSottile** [comment]
Glad to hear this was resolved!
