### ISSUE TITLE
Self-check failures on mips64el

### ISSUE THREAD

**Issue by jas4711** [FiloSottile/age#609]
Hi!  I've uploaded both age 1.2.0 and 1.2.1 to Debian and the 1.2.0 version built fine, but 1.2.1 has a self-check failure that only occurs on mips:

```
=== NAME  TestScript/ed25519
    testscript.go:558: WORK=$WORK
        PATH=/tmp/testscript-main1166321793/bin:/usr/lib/go-1.23/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
        GOTRACEBACK=system
        HOME=/no-home
        TMPDIR=$WORK/.tmp
        devnull=/dev/null
        /=/
        :=:
        $=$
        exe=
        
        # encrypt and decrypt a file with -R (0.121s)
        > age -R key.pem.pub -o test.age input
        > age -d -i key.pem test.age
        [stdout]
        test
        > cmp stdout input
        > ! stderr .
        # encrypt and decrypt a file with -i (0.032s)
        > age -e -i key.pem -o test.age input
        [stderr]
        age: error: read input: bad address
        age: report unexpected or unhelpful errors at https://filippo.io/age/report
        [exit status 1]
        FAIL: testdata/ed25519.txt:8: unexpected command failure
```

You can see several more of the same error here:

https://buildd.debian.org/status/fetch.php?pkg=age&arch=mips64el&ver=1.2.1-1&stamp=1734614497&raw=0

Do you have any ideas how to debug this further?

It is fully possible that some build dependency of age has been upgraded in Debian between the 1.2.0 and 1.2.1 uploads, and that the change on that build dependency is causing the breakage.  So we shouldn't assume 1.2.0 would still build in Debian.  I'm trying to arrange access to some mips machine for further debugging, but I'm really beyond my knowledge here so I'm reaching out looking for help.

Thanks,
Simon

**Comment by FiloSottile** [comment]
That looks really weird: a read from the `input` file is getting a EFAULT. age uses a very simple `os.Open` followed by an `io.Copy` so it's hard to imagine this would be age-specific, and there are no dependencies involved aside from Go. Also note how the previous invocation works, for the same binary and input file. There's either something wrong with the hardware, or with the Go compiler or runtime.
