### ISSUE TITLE
UX: RECIPIENT

### ISSUE THREAD

**Issue by proyb6** [FiloSottile/age#61]
## What were you trying to do
Tried to understand the purpose of RECIPIENT

What will it happen if someone tried to brute force with RECIPIENT key, are the mechanism to avoid encrypted files in form of binary or plaintext from being decrypt?

**Comment by wfRbeHBASpPKniSGBUvZ** [comment]
Recipients' public keys are 62 alphanumeric characters long (although they all begin with 'age1' as far as I can tell) and I think that length rules out brute forcing. I'm not a domain expert, so hopefully someone else can add more insight.

**Comment by proyb6** [comment]
I seen it also use Scrypt on passphrase which made brute force inefficient.
