### ISSUE TITLE
UX: Show usage on naked command

### ISSUE THREAD

**Issue by Brcrwilliams** [FiloSottile/age#74]
## What were you trying to do

Show the usage documentation.

## What happened

```
$ age
Error: missing recipients.
Did you forget to specify -r/--recipient or -p/--passphrase?
[ Did age not do what you expected? Could an error be more useful? Tell us: https://filippo.io/age/report ]
```

## Additional detail

Right after installing age, most people are going want to see the usage output. It makes for a better user experience if you show the usage / help for all things that the user might try, instead of making the user try multiple different flags to get the usage to appear.

I'd suggest displaying the usage output when age is run with any of the following arguments:

- `age`
- `age help`
- `age --help`
- `age -h`

**Comment by randyqx** [comment]
would also be nice if `age --help` was directed to stdout not stderr

**Comment by Brcrwilliams** [comment]
Why's that?
Generally, outputting usage to stdout is not ideal, because if you are piping stdout then you won't see it.

For example, if I'm trying to decrypt a file and accidentally include the `-h` flag:
```sh
age -h -d file.age > file
```

The problem won't be immediately evident because the usage output will get directed into the file instead of showing on my terminal.
