### ISSUE TITLE
umask in warning message is confusing

### ISSUE THREAD

**Issue by str4d** [FiloSottile/age#75]
https://github.com/FiloSottile/age/blob/e43cf8b4a2d571df8dcb30783a460acbf188adb4/cmd/age-keygen/keygen.go#L41-L42

`066` sets the file to writable by group and everyone but not the user. I think it's meant to be `0660`.

**Comment by magical** [comment]
It looks right to me as is. umask is an inverse mask of the permission bits, so a umask of 066 should clear the read and write bits of any new files for the group and other users but not the owner.

**Comment by str4d** [comment]
> umask is an inverse mask of the permission bits

That's a very good point; the error message does say "umask", not "mode". That is terribly unusable; I know of no way to directly set a umask in the CLI, whereas I expect every user will turn to `chmod` and stick that value in (as I did), because it looks so close to a common mode.

Perhaps the error should instead give an example command for the user to run? Either one that uses the umask, or a `chmod 600 FILENAME`.

**Comment by magical** [comment]
> I know of no way to directly set a umask in the CLI

    $ umask 066

should work in any POSIX shell.

**Comment by magical** [comment]
I believe the reason the warning suggests `umask` instead of `chmod` is so that the file will never exist with too-broad permissions. If you chmod it after the fact, another user on the machine could read the contents between when the key is generated and when the permissions are changed.

**Comment by magical** [comment]
Perhaps an better solution is to suggest that users use the `-o` option to specify the output file, in which case `age` creates the file, not the shell, and can set the correct permissions.

**Comment by Maryse47** [comment]
I think the warning is indeed confusing but for different reason: umask should be `077`.

`066` will leave execution rights which doesn't make sense.

**Comment by str4d** [comment]
> ```
> $ umask 066
> ```
> should work in any POSIX shell.

Oh cool, this is something I'd never come across! Which exactly makes my point: the error message shouldn't assume that users are familiar with obscure Unix-specific functionality.

**Comment by psanford** [comment]
@str4d did you actually trigger the error message here? The code is already creating the file with limited permissions:
```
f, err := os.OpenFile(name, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0600)
```
Its then doing a sanity check on the permissions after creation. 

Given the `0600` FileMode It doesn't seem like it would be possible to actually hit this error case on a normal unix filesystem. (If you did somehow hit this error I don't see how the problem would actually be related to the process' umask).

**Comment by magical** [comment]
@psanford That code only applies if you use the `-o` option. If you redirect the output of `age-keygen` to a file, the shell creates the file and you can see the warning.

```
% umask         
002
% ./age-keygen >test.keys
Warning: writing to a world-readable file.
Consider setting the umask to 066 and trying again.
Public key: age1efnk2yn5zj0zffkthqsmzz7gv5e7gffkpqlmsg76qlger0satasscpg3zj
% ls -l test.keys 
-rw-rw-r--. 1 foo bar 189 Jan  2 11:25 test.keys
```
