### ISSUE TITLE
Autogenerated passphrase

### ISSUE THREAD

**Issue by Fastidious** [FiloSottile/age#78]
## Environment

* OS: macOS
* age version: Latest on brew

## What were you trying to do

Following the example on README.md, `age -p secrets.txt > secrets.txt.age`.

## What happened

This:

```
dreadnought: fastidious$ age -p secrets.txt > secrets.txt.age
Enter passphrase:
Error: empty scrypt password
[ Did age not do what you expected? Could an error be more useful? Tell us: https://filippo.io/age/report ]
```

There is no more autogenerated password?

**Comment by Fastidious** [comment]
Sure enough, it is. Thanks!

**Comment by graphixillusion** [comment]
I got the same problem: i've compiled from source but when it stucks at:

**Enter passphrase (leave empty to autogenerate a secure one):**

Enter key doesn't work, even if you type something then enter. You can only do a ctlr-c to force close.

**Comment by FiloSottile** [comment]
@graphixillusion Ah, this is golang/go#36609, I updated x/crypto to bring in the fix. Please open a new issue if it's still a problem.

**Comment by graphixillusion** [comment]
@FiloSottile thank you very much for the super fast fix. now it works as expected.
