### ISSUE TITLE
[spec] scrypt doesn't specify an output length

### ISSUE THREAD

**Issue by str4d** [FiloSottile/age#8]
The `scrypt` definition has no length parameter, but references RFC 7914 which specifies that the output length is variable within bounds. In practice it is constrained by its sole usage as an input to `encrypt` (which per RFC 7539 takes a 256-bit key), but this is inconsistent with the specification of `hkdf` (which is similarly only used for 256-bit outputs but has an explicit length parameter). To save on indirection, the spec should either add an an explicit length parameter to `scrypt`, or just hard-code the 32-byte length in the definitions of `scrypt` and `hkdf`.

**Comment by FiloSottile** [comment]
Fixed by defining both as 32 bytes. Thank you. (HKDF is also used as an HMAC key which has no implicit length.)
