### ISSUE TITLE
Padmé padding for age?

### ISSUE THREAD

**Issue by colmmacc** [FiloSottile/age#83]
I was tempted to open this as a bug, but that would be provocative: age does not make an effort to hide the size of the encrypted payload. Since many sensitive payloads can be identified by their size alone, this has obvious privacy implications. 

The PURB paper ([https://bford.info/pub/sec/purb.pdf)](https://bford.info/pub/sec/purb.pdf)) defines an interesting padding scheme called Padmé that introduces at most 12% overhead, and where the overhead decreases with file size.  The key quote from the paper Is ...

> We show that Padmé can significantly reduce the number of objects uniquely identifiable by their sizes: from 83% to 3% for 56k Ubuntu packages, from 87% to 3% for 191k Youtube videos, from 45% to 8% for 848k hard-drive user files, and from 68% to 6% for 2.8k websites from the Alexa top 1M list. This much stronger leakage protection in- curs an average space overhead of only 3%.

To my mind, adding 3% overhead for a ~5x improvement in file obfuscation is more than worth it, and that's the worst performing of the examples. 

There are Go implementations already, for example: https://github.com/dedis/purb/blob/master/purbs/padding.go

it certainly doesn't look like a big performance hit or anything like that. Is a padding scheme like this something that would be considered for age?

I'm happy to work on adding it myself, in Go and rust. I've opened this issue for discussion.

**Comment by cyb3rz3us** [comment]
> sensitive payloads can be identified by their size alone

Help me understand how this works for many of the targets that would be encrypted by 'age'?

For example, if I have a TAR-ball that is comprised of say 5000 pictures and when encrypted, it might come in around 25GB.  If I then have another TAR-ball of documents, if mght come in when encrypted at around 12GB, then how is the size of the payload helping to identify the payload?

I'm sure there's something I'm not understanding so please receive my question as only seeking to understand...not push-back...

**Comment by colmmacc** [comment]
Well let's say that the tarball is 'illegal' material that you have an interest in denying possession of. There are awful and cruel examples of this, but there are also righteous and good examples of this. For example the encrypted file might be the 'Bible' for a religion that an oppressive state has made illegal to possess, or it might be a tarball of material that a (corporate or state) whistle-blower leaked to a news-organization.  

Without any padding, an exact byte-match of the illicit material is extremely suggestive circumstantial evidence of possession. With well-crafted padding; there is a greater range of potential content that encrypts to that size and the match is not as definitive.

**Comment by colmmacc** [comment]
I should add too that padding can be a useful mitigation against another kind of attack: shared compression tables.

Suppose that the tarball is a gzipped backup of your email inbox and that you make that backup every day and send it to a Cloud service for storage. The size of the backup can be seen by anyone who can observe the upload.

Now suppose I send you an email every day; and also observe the size of the backup. Over time, by trying different strings in my email, I can statistically profile where there Is overlap between the strings in my email, and other strings in your inbox (other emails); or at least the frequency of them. This is because the compression table entries will be shared, and so when there's overlap the output size is smaller than I would otherwise expect it to be.  Exposing exact payload sizes make these kinds of shared-compression-table makes the attacks very practical. 

For example: suppose I send you a 200 byte email that contains the string "TOP SECRET DOCUMENTS", over the weekend when you're not getting much other email, and the size of your backup only goes up by 12 bytes, I can guess that the string "TOP SECRET DOCUMENTS" appears elsewhere in your inbox. 

Padding doesn't prevent these attacks; the attacker can pad themselves until the email crosses a padding boundary, helps makes these attacks much more costly and slow and only one bit of information is leaked each time a padding boundary is crossed, so it's just not nearly as practical.

**Comment by cyb3rz3us** [comment]
Taking the second set of comments first, as you mentioned, padding does nothing to prevent that type of attack.  Also, what you outline is an attack far beyond the scope of 'age' or really any tool used for encryption.

Now, the first set of comments...I'm not sure I see how we get from knowing an exact byte count to knowing for certain that a given encrypted file is an actual work.  I really don't care that much if an interloper knows what a given encrypted file may contain.  This bring them no closer to decrypting the file without my consent which is really all I care about when considering what I expect from 'age'.

There may be a path such as: **encryptedFile** + **iKnowWhatTheFileMayContain** --> **DECRYPTED** --- I'm just not sure one exists...but if it does, then I think we're in trouble... :=)

**Comment by colmmacc** [comment]
In context that's absolutely not what I wrote, but I should have been more careful not to say 'prevent' so casually. For compression attacks, sufficient padding does increase the costs for attackers, well beyond practicality in most cases. One bit per padding length is very very low bandwidth with which to try and work out the compression table collision.

Sounds like in your threat model that you don't care about an attacker being able to identify the plaintext from a set of known plaintexts. That's ok, but it's a pretty non-standard assumption.

**Comment by cyb3rz3us** [comment]
I don't see this as particularly "my threat model"...I see as the likely threat models that are relevant to the typical user of 'age'.  The issue you describe is more of a privacy concern as opposed to an encryption concern and again, my interpretation of FiloSottie's writing re: PGP and the reason why 'age' was developed in the first place, I view 'age' as an encryption tool...nothing more.  That's not to say it can't be more but then that is really the dev's decision...
