### ISSUE TITLE
UX: Encrypt private key by default

### ISSUE THREAD

**Issue by johnalanwoods** [FiloSottile/age#86]
## What were you trying to do

I was playing with the Age beta, generating keys

## What happened
I think that in spite of solid UNIX file permissions, the default behaviour should be to encrypt private keys with a symmetric key derived from a password.

Is there an intention to add this feature to Age? If not how best should users. secure plaintext private key material?

Reading the document on Age I see:

> Maybe native support for key wrapping (to implement password-protected keys)

However surely that's a fundamental need, otherwise private key material sits in plaintext.

**Comment by cyb3rz3us** [comment]
FWIW, I gen my keypairs using ssh-keygen but agreed that enhancing the age-keygen w/ encrypted private keys would be nice as long as not mandated.

**Comment by johnalanwoods** [comment]
@cyb3rz3us - that's a nice approach, so you get encrypted private keys, however, can you use the ssh-gen private key with age directly?

(if so I guess ok once it's an ed25519 key.

**Comment by cyb3rz3us** [comment]
>  can you use the ssh-gen private key with age directly

By all means.  However, as with the 'age' keys, when encrypting, you will need to include the public key data on the command line which as oyu can imagine, can be quite cumbersom especially for keys > 1024.  There is a ticket open to enable specifying the pub key as a file but it is apparently not yet working.

That said, this does work on the decrypt side --- the private key file can be specified using the '-i' switch and if the key is PW protected, then you will be prompted for the password.

> once it's an ed25519 key

Not sure what you mean here?  The payload encryption key is not generate by the keygen app...that is still done by 'age'.

**Comment by vext01** [comment]
> However surely that's a fundamental need, otherwise private key material sits in plaintext.

I agree.

I'm trying hard to ditch gpg for something else. One contender is opmsg, but the lack of protection for private key material puts me off:

> The private part of the keys which are stored inside ~/.opmsg are NOT encrypted. It is believed that once someone gained access to your account, its all lost anyway.

I disagree with the above. No one has gained access to my system, but I do run lots of software on my system, and any one of them may try to steal private keys.

[When I first looked at age, I had planned to simply use my SSH private key, but sadly it resides on a yubikey, which can't yet be used with age. So a regular encrypted age key might be a good stepping stone until ssh-agent support is integrated. Agent support would be ideal though, as I'd only have to unlock the private key once.]

**Comment by infa-jowoods** [comment]
Would @FiloSottile take a PR on this? I'm happy to take a stab at it.

**Comment by vext01** [comment]
There's one linked above, but it seems to have stalled.

**Comment by codesoap** [comment]
I, too, like to encrypt my keys most of the time, but I can also see how implementing this here would hurt the simplicity of `age`. `age` already provides all features to create password-secured keys ourselves. This is how it could work (we could, of course, write our own scripts to simplify this):

```console
$ printf 'foo\n' > testdata
$ age-keygen | age -p -o mykey.age
Public key: age1j85xmnxgavcach38x4nnzu2tcmdnj7vqq2d4ffmwjsdh9flcuy9sa8agsm
Enter passphrase (leave empty to autogenerate a secure one): mysecret
Confirm passphrase: mysecret
$ age -o testdata.age -r age1j85xmnxgavcach38x4nnzu2tcmdnj7vqq2d4ffmwjsdh9flcuy9sa8agsm testdata
$ AGE_SECRET=$(age -d mykey.age)
$ age -d -i <(printf "$AGE_SECRET") testdata.age
foo
```

However, there is one big flaw: The bashism `<()` (process substitution) needs to be used to fake a file for `-i`. This is not very portable and potentially also insecure (I'm not sure). It would be a lot better, if `age` would read the environment variable `AGE_SECRET` directly. This is not yet implemented, but would be a lot simpler than #132 and @FiloSottile [seems to have intended something like this](https://github.com/FiloSottile/age/blob/31500bfa2f6a36d2958483fc54d6e3cc74154cbc/age.go#L24) anyway.

**Comment by Fastidious** [comment]
@codesoap, is there a way to save output on decryption instead of STDOUT? I know one can do:

```
age -d mykey.age | age -d -i - testdata.age > testdata
```

But I wonder if there is a way using the `-o` flag. I tried a few combinations unsuccessfully.

**Comment by CHTJonas** [comment]
> is there a way to save output on decryption instead of STDOUT? [...] I wonder if there is a way using the `-o` flag. I tried a few combinations unsuccessfully.

Weird. Using `-o` works fine for me:

```bash
age -d mykey.age | age -d -i - -o testdata.2 testdata.age
```
