### ISSUE TITLE
UX: Specification of encryption format

### ISSUE THREAD

**Issue by johnalanwoods** [FiloSottile/age#87]
## What were you trying to do
Understand the encrypted file formats to integrate with Age

## What happened
I can't seem to find a spec for the formats, such as:

Which ciphers (RSA, Ed25519/cv25519 are implemented as Ephemeral:Ephemeral vs Ephemeral:Static...

How the output Age encryption PEM/armor is structured to include the ephemeral public key components.

**Comment by FiloSottile** [comment]
The spec is at https://age-encryption.org/v1. Please open a new issue if you find anything missing!
