### ISSUE TITLE
Password decryption not working

### ISSUE THREAD

**Issue by Fastidious** [FiloSottile/age#90]
## Environment

* OS: macOS
* age version: Compiled from `master` on 09 January 2020.

## What were you trying to do

Use `age` for symmetric encryption of a file.

## What happened

```
dreadnought$ age -a -p secrets.txt
Enter passphrase (leave empty to autogenerate a secure one):
Using the autogenerated passphrase "session-click-base-source-purpose-priority-ramp-delay-belt-buyer".
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNjcnlwdCAvcnk3SHdqQ0xaZEZTaDJT
NGZYOUl3IDE4CnA3Y2pjRWI0Q3FVNUVuWE0rdTdON2hyME5hZFhTeWdFM3FqOTFI
ajR1OFkKLS0tIEZQQ2FxU3dDMFA3K0xOd2N1SktVV1IwSWVJTzV5MU5JUWFpWEYv
T1JqeXMKf40JHd82a/AyeRZddrALDGTsCwVmJJQYLsQAAxyctA9ZsgAuGV0Oc4ye
+Mc=
-----END AGE ENCRYPTED FILE-----
dreadnought$ age -d secrets.txt.age > plain.txt
Error: no identity matched a recipient
[ Did age not do what you expected? Could an error be more useful? Tell us: https://filippo.io/age/report ]
dreadnought$
```

**Comment by cyb3rz3us** [comment]
Just curious, when trying to reproduce this, I found I had to either **(a)** save the encrypted output to an actual file; or **(b)** specify the file for the encrypted output using the '-o' switch.

When I did either of the above, the decrypt worked fine for me.

Do you perhaps have an old **'secrets.txt.age'** file hanging around?

**Comment by Fastidious** [comment]
Bingo! Yes, I assumed the file `secrets.txt.age` was being created, when indeed it wasn't, but an old one encrypted with an ssh key laid around.

It would be best if the file were saved as default, instead of just spit on terminal. Should I leave this open for further dialogue, or close?

**Comment by cyb3rz3us** [comment]
Well, my reading of the help section is that to create the output file, the '-o' switch is required.  Perhaps I am misreading it but that's my understanding.

That said, maybe a good idea to leave open for a few other comments and\or discussion.

**Comment by Fastidious** [comment]
@cyb3rz3us you can also redirect the output to a file (`>`), without using `-o`.

**Comment by cyb3rz3us** [comment]
Agreed - I should have instead stated that the output file must be specified on the CLI.
