### ISSUE TITLE
Can age encrypt email messages instead of just files?

### ISSUE THREAD

**Issue by PowerPress** [FiloSottile/age#93]
Can age encrypt email messages instead of just files?

**Comment by Fastidious** [comment]
Use `age` with `-a` option on a file with the text of your email, and use the resultant file content as the email itself. Easily done automatically if using `mutt` or similar email client.

**Comment by moritzdietz** [comment]
Please take a look at the spec at https://age-encryption.org/v1 and see the section "Out of scope"
> Anything about emails (which are a fundamentally unsecurable medium)
Though, you can encrypt text and put the encrypted file in an E-Mail, but this is nothing like S/MIME or GPG encrypted E-Mails.
